package com.example.demo.model.mapper;

import com.example.demo.model.HihatuWorktbl;
import com.example.demo.model.HihatuWorktblExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HihatuWorktblMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hihatu_worktbl
	 * @mbg.generated  Sun Aug 07 13:16:00 JST 2022
	 */
	long countByExample(HihatuWorktblExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hihatu_worktbl
	 * @mbg.generated  Sun Aug 07 13:16:00 JST 2022
	 */
	int deleteByExample(HihatuWorktblExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hihatu_worktbl
	 * @mbg.generated  Sun Aug 07 13:16:00 JST 2022
	 */
	int deleteByPrimaryKey(Integer hid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hihatu_worktbl
	 * @mbg.generated  Sun Aug 07 13:16:00 JST 2022
	 */
	int insert(HihatuWorktbl row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hihatu_worktbl
	 * @mbg.generated  Sun Aug 07 13:16:00 JST 2022
	 */
	int insertSelective(HihatuWorktbl row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hihatu_worktbl
	 * @mbg.generated  Sun Aug 07 13:16:00 JST 2022
	 */
	List<HihatuWorktbl> selectByExample(HihatuWorktblExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hihatu_worktbl
	 * @mbg.generated  Sun Aug 07 13:16:00 JST 2022
	 */
	HihatuWorktbl selectByPrimaryKey(Integer hid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hihatu_worktbl
	 * @mbg.generated  Sun Aug 07 13:16:00 JST 2022
	 */
	int updateByExampleSelective(@Param("row") HihatuWorktbl row, @Param("example") HihatuWorktblExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hihatu_worktbl
	 * @mbg.generated  Sun Aug 07 13:16:00 JST 2022
	 */
	int updateByExample(@Param("row") HihatuWorktbl row, @Param("example") HihatuWorktblExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hihatu_worktbl
	 * @mbg.generated  Sun Aug 07 13:16:00 JST 2022
	 */
	int updateByPrimaryKeySelective(HihatuWorktbl row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hihatu_worktbl
	 * @mbg.generated  Sun Aug 07 13:16:00 JST 2022
	 */
	int updateByPrimaryKey(HihatuWorktbl row);
}